1 feature monitor and message receiver
Team-DDev/bitsql pull request #2
Opened 2022-05-10 07:53 UTC by Yujin-nKim

2022-05-10 23:15 UTC, munhyunsu commented
Things I think should be fixed.

1. Each file must end with `breakline`. (File coding convention)
2. The standard library of `import` and the 3rd-party library should be separated by one breakline. (Coding convention)
3. Functions (`def`) and `import`, `if __name__ == '__main__'` should be separated by two breaklines. (Coding convention)
4. In the `if __name__ == '__main__'` division, it should be designed in advance so that argument parsing using argparse is possible.
4-2. In particular, since these two codes are the main process, `parameter parsing' must be enabled.
4-3. [Note](https://github.com/munhyunsu/Hobby/blob/master/StarterCode/main.py)
5. `test.py` contains the account name and password. You need to change it to secret.py and import the file to use it.
5-2. The password has been leaked online, so you need to change your password!
6. Both `message_receiver.py` and `Monitor.py` should handle graceful exit with `try-except KeyboardInterrupt`
7. All file names need to be modified. (Coding convention)
7-2. Suggestion: `main_monitor.py` `main_blockhandler.py`
8. Requires `requirements.txt` what 3rd-party library is required!

- Ref [Google Python Style Guide](http://eiichiroi.github.io/google-styleguide-ja/pyguide.html)

2022-05-10 23:21 UTC, munhyunsu requested changes
Things I think should be fixed.

1. Each file must end with `breakline`. (File coding convention)
2. The standard library of `import` and the 3rd-party library should be separated by one breakline. (Coding convention)
3. Functions (`def`) and `import`, `if __name__ == '__main__'` should be separated by two breaklines. (Coding convention)
4. In the `if __name__ == '__main__'` division, it should be designed in advance so that argument parsing using argparse is possible.
4-2. In particular, since these two codes are the main process, `parameter parsing' must be enabled.
4-3. [Note](https://github.com/munhyunsu/Hobby/blob/master/StarterCode/main.py)
5. `test.py` contains the account name and password. You need to change it to secret.py and import the file to use it.
5-2. The password has been leaked online, so you need to change your password!
6. Both `message_receiver.py` and `Monitor.py` should handle graceful exit with `try-except KeyboardInterrupt`
7. All file names need to be modified. (Coding convention)
7-2. Suggestion: `main_monitor.py` `main_blockhandler.py`
8. Requires `requirements.txt` what 3rd-party library is required!

- Ref [Google Python Style Guide](http://eiichiroi.github.io/google-styleguide-ja/pyguide.html)

2022-05-10 23:21 UTC, munhyunsu commented on Monitor.py
> +    rpc_connection = AuthServiceProxy("http://%s:%s@127.0.0.1:8332" % ("yujin", "dnlab2022"))
Personal information exposure code: Need to use `secret.py`

2022-05-10 23:21 UTC, munhyunsu commented on Monitor.py
> +
unnecessary breaklines

2022-05-11 07:24 UTC, Yujin-nKim commented
수정완료했습니다.

2022-05-11 07:30 UTC, munhyunsu approved these changes

2022-05-11 07:31 UTC, merged